#!/bin/sh

rm -f Medo
rm -f *.o
rm -f Editor/*.o
rm -f Effects/*.o
rm -f Gui/*.o
rm -f Actor/*.o
rm -f Yarra/FileIO/*.o
rm -f Yarra/Math/*.o
rm -f Yarra/Platform/*.o
rm -f Yarra/Render/*.o
rm -f Yarra/FreeTypeGL/*.o
rm -f Yarra/FreeTypeGL/libtess/*.o
rm -rf build
rm -rf Package

rm -rf CMakeFiles
rm -rf .cmake
rm -f CMakeCache.txt
rm -f cmake_install.cmake
rm -f CMakeLists.txt.user
rm -f Makefile


